# Рубежный контроль 2

 Фильчиков Артём РТ5-61

 Вариант 19

In [299]:
import sklearn
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import math as mth
import matplotlib.patches as patches
from scipy import stats as st
plt.rcParams.update({'figure.max_open_warning': 0})
import plotly.graph_objects as go
import plotly.express as px
from sklearn.preprocessing import StandardScaler
pd.options.mode.chained_assignment = None
from sklearn.ensemble import GradientBoostingClassifier, GradientBoostingRegressor

from pandas import plotting
from scipy import stats
plt.style.use("ggplot")
#import warnings
#warnings.filterwarnings("ignore")


# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os

In [300]:
df = pd.read_csv(r"C:\Users\artfi\ML\RK2\investmentsVC.csv",encoding='latin1')
df = df.replace(',', '.', regex=True)
df = df.replace(' ', '', regex=True)

In [301]:
df

,permalink,name,homepage_url,category_list,market,funding_total_usd,status,country_code,state_code,region,...,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H
0,/organization/waywire,#waywire,http://www.waywire.com,|Entertainment|Politics|SocialMedia|News|,News,17.50.000,acquired,USA,NY,NewYorkCity,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,/organization/tv-communications,&TVCommunications,http://enjoyandtv.com,|Games|,Games,40.00.000,operating,USA,CA,LosAngeles,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,/organization/rock-your-paper,'Rock'YourPaper,http://www.rockyourpaper.org,|Publishing|Education|,Publishing,40.000,operating,EST,NaN,Tallinn,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,/organization/in-touch-network,(In)TouchNetwork,http://www.InTouchNetwork.com,|Electronics|Guides|Coffee|Restaurants|Music|i...,Electronics,15.00.000,operating,GBR,NaN,London,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,/organization/r-ranch-and-mine,-R-RanchandMine,NaN,|Tourism|Entertainment|Games|,Tourism,60.000,operating,USA,TX,Dallas,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54289,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54290,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54291,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54292,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54293,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Для сокращения времени работы выберем для работы фрагмент датасета из 1000 строк

In [302]:
df = df.head(1000)

In [303]:
df

,permalink,name,homepage_url,category_list,market,funding_total_usd,status,country_code,state_code,region,...,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H
0,/organization/waywire,#waywire,http://www.waywire.com,|Entertainment|Politics|SocialMedia|News|,News,17.50.000,acquired,USA,NY,NewYorkCity,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,/organization/tv-communications,&TVCommunications,http://enjoyandtv.com,|Games|,Games,40.00.000,operating,USA,CA,LosAngeles,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,/organization/rock-your-paper,'Rock'YourPaper,http://www.rockyourpaper.org,|Publishing|Education|,Publishing,40.000,operating,EST,NaN,Tallinn,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,/organization/in-touch-network,(In)TouchNetwork,http://www.InTouchNetwork.com,|Electronics|Guides|Coffee|Restaurants|Music|i...,Electronics,15.00.000,operating,GBR,NaN,London,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,/organization/r-ranch-and-mine,-R-RanchandMine,NaN,|Tourism|Entertainment|Games|,Tourism,60.000,operating,USA,TX,Dallas,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,/organization/adchoice,AdChoice,http://www.adchoiceinc.com/,|Networking|,Networking,-,operating,USA,CA,SanDiego,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
996,/organization/adcole-corporation,AdcoleCorporation,http://www.adcole.com,|Industrial|Manufacturing|Aerospace|,Industrial,-,acquired,USA,MA,Boston,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
997,/organization/adconion-media-group,AdconionMediaGroup,http://www.adconion.com,|Entertainment|AdTargeting|Advertising|,Entertainment,11.40.00.000,acquired,USA,CA,LosAngeles,...,0.0,0.0,0.0,0.0,80000000.0,0.0,0.0,0.0,0.0,0.0
998,/organization/adcrimson,AdCrimson,http://www.adcrimson.com,|Email|Mobile|Advertising|,Email,-,operating,PHL,NaN,Manila,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
999,/organization/adcrowd-retargeting,Adcrowdretargeting,http://www.adcrowd.com,|AdTargeting|Advertising|,AdTargeting,7.33.372,operating,NLD,NaN,Amsterdam,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## Удалим пропуски:

In [304]:
def draw_missing(df):
    total = df.isnull().sum().sort_values(ascending=False)
    percent = (df.isnull().sum()/df.isnull().count()).sort_values(ascending=False)*100
    missing_data = pd.concat([total, percent], axis=1, keys=['Total', 'Percent'])
    return missing_data

In [305]:
draw_missing(df).round(1)

                      Total  Percent
state_code              413     41.3
founded_at              212     21.2
founded_year            212     21.2
founded_quarter         212     21.2
founded_month           212     21.2
city                    127     12.7
country_code            103     10.3
region                  103     10.3
 market                  77      7.7
category_list            77      7.7
homepage_url             71      7.1
status                   19      1.9
round_C                   0      0.0
post_ipo_debt             0      0.0
secondary_market          0      0.0
product_crowdfunding      0      0.0
round_A                   0      0.0
round_B                   0      0.0
permalink                 0      0.0
round_D                   0      0.0
round_E                   0      0.0
private_equity            0      0.0
round_F                   0      0.0
round_G                   0      0.0
post_ipo_equity           0      0.0
venture                   0      0.0
grant                     0      0.0
angel                     0      0.0
debt_financing            0      0.0
convertible_note          0      0.0
undisclosed               0      0.0
equity_crowdfunding       0      0.0
name                      0      0.0
seed                      0      0.0
last_funding_at           0      0.0
first_funding_at          0      0.0
funding_rounds            0      0.0
 funding_total_usd        0      0.0
round_H                   0      0.0

В колонке company присутствует 94% пропуска, значит для анализа столбец бесполезен. Удалим его из набора данных:

In [306]:
df=df.drop('state_code', axis=1)

Удалим пропуски:

In [307]:
df = df.dropna()

In [308]:
draw_missing(df).round(1)

                      Total  Percent
permalink                 0      0.0
secondary_market          0      0.0
convertible_note          0      0.0
debt_financing            0      0.0
angel                     0      0.0
grant                     0      0.0
private_equity            0      0.0
post_ipo_equity           0      0.0
post_ipo_debt             0      0.0
product_crowdfunding      0      0.0
name                      0      0.0
round_A                   0      0.0
round_B                   0      0.0
round_C                   0      0.0
round_D                   0      0.0
round_E                   0      0.0
round_F                   0      0.0
round_G                   0      0.0
undisclosed               0      0.0
equity_crowdfunding       0      0.0
venture                   0      0.0
seed                      0      0.0
homepage_url              0      0.0
category_list             0      0.0
 market                   0      0.0
 funding_total_usd        0      0.0
status                    0      0.0
country_code              0      0.0
region                    0      0.0
city                      0      0.0
funding_rounds            0      0.0
founded_at                0      0.0
founded_month             0      0.0
founded_quarter           0      0.0
founded_year              0      0.0
first_funding_at          0      0.0
last_funding_at           0      0.0
round_H                   0      0.0

Удалим колонки с уникальными значениями:

In [309]:
df

,permalink,name,homepage_url,category_list,market,funding_total_usd,status,country_code,region,city,...,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H
0,/organization/waywire,#waywire,http://www.waywire.com,|Entertainment|Politics|SocialMedia|News|,News,17.50.000,acquired,USA,NewYorkCity,NewYork,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,/organization/rock-your-paper,'Rock'YourPaper,http://www.rockyourpaper.org,|Publishing|Education|,Publishing,40.000,operating,EST,Tallinn,Tallinn,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,/organization/in-touch-network,(In)TouchNetwork,http://www.InTouchNetwork.com,|Electronics|Guides|Coffee|Restaurants|Music|i...,Electronics,15.00.000,operating,GBR,London,London,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,/organization/004-technologies,004Technologies,http://004gmbh.de/en/004-interact,|Software|,Software,-,operating,USA,Springfield.Illinois,Champaign,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,/organization/1-2-3-listo,1.2.3Listo,http://www.123listo.com,|E-Commerce|,E-Commerce,40.000,operating,CHL,Santiago,LasCondes,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,/organization/adchina,AdChina,http://adchina.com,|Advertising|,Advertising,1.00.00.000,operating,CHN,Shanghai,Shanghai,...,0.0,0.0,10000000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
995,/organization/adchoice,AdChoice,http://www.adchoiceinc.com/,|Networking|,Networking,-,operating,USA,SanDiego,Carlsbad,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
997,/organization/adconion-media-group,AdconionMediaGroup,http://www.adconion.com,|Entertainment|AdTargeting|Advertising|,Entertainment,11.40.00.000,acquired,USA,LosAngeles,SantaMonica,...,0.0,0.0,0.0,0.0,80000000.0,0.0,0.0,0.0,0.0,0.0
998,/organization/adcrimson,AdCrimson,http://www.adcrimson.com,|Email|Mobile|Advertising|,Email,-,operating,PHL,Manila,Makati,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
999,/organization/adcrowd-retargeting,Adcrowdretargeting,http://www.adcrowd.com,|AdTargeting|Advertising|,AdTargeting,7.33.372,operating,NLD,Amsterdam,Amsterdam,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [310]:
df=df.drop('permalink', axis=1)
df=df.drop('name', axis=1)
df=df.drop('homepage_url', axis=1)

## Закодируем категориальные признаки:

In [311]:
from sklearn.preprocessing import LabelEncoder

In [312]:
le = LabelEncoder()
for col in df.columns:
    column_type = df[col].dtype
    if column_type == 'object':
        df[col] = le.fit_transform(df[col])
        print(col)

category_list
 market
 funding_total_usd
status
country_code
region
city
founded_at
founded_month
founded_quarter
first_funding_at
last_funding_at

## Отмасштабируем данные:

In [313]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler, Normalizer

In [314]:
df

,category_list,market,funding_total_usd,status,country_code,region,city,funding_rounds,founded_at,founded_month,...,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H
0,96,104,117,0,42,109,188,1.0,168,118,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,213,118,254,2,16,162,274,1.0,174,122,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,87,50,100,2,19,85,153,1.0,140,106,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,255,137,0,2,42,154,52,1.0,112,91,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,80,47,254,2,8,146,141,1.0,153,113,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,5,4,1,2,9,150,253,3.0,66,62,...,0.0,0.0,10000000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
995,182,103,0,2,42,144,48,1.0,118,93,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
997,94,53,79,0,42,87,246,3.0,51,48,...,0.0,0.0,0.0,0.0,80000000.0,0.0,0.0,0.0,0.0,0.0
998,90,51,0,2,32,92,163,1.0,134,103,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
999,3,3,333,2,29,5,5,1.0,153,113,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [315]:
sc1 = MinMaxScaler()
df['category_list'] = sc1.fit_transform(df[['category_list']])
df[' market '] = sc1.fit_transform(df[[' market ']])
df[' funding_total_usd '] = sc1.fit_transform(df[[' funding_total_usd ']])
df['status'] = sc1.fit_transform(df[['status']])
df['country_code'] = sc1.fit_transform(df[['country_code']])
df['region'] = sc1.fit_transform(df[['region']])
df['city'] = sc1.fit_transform(df[['city']])
df['funding_rounds'] = sc1.fit_transform(df[['funding_rounds']])
df['founded_at'] = sc1.fit_transform(df[['founded_at']])
df['round_A'] = sc1.fit_transform(df[['round_A']])
df['round_B'] = sc1.fit_transform(df[['round_B']])
df['round_C'] = sc1.fit_transform(df[['round_C']])
df['round_D'] = sc1.fit_transform(df[['round_D']])
df['round_E'] = sc1.fit_transform(df[['round_E']])
df['round_F'] = sc1.fit_transform(df[['round_F']])
df['round_G'] = sc1.fit_transform(df[['round_G']])
df['round_H'] = sc1.fit_transform(df[['round_H']])
df['debt_financing'] = sc1.fit_transform(df[['debt_financing']])
df['angel'] = sc1.fit_transform(df[['angel']])
df['grant'] = sc1.fit_transform(df[['grant']])
df['private_equity'] = sc1.fit_transform(df[['private_equity']])
df['post_ipo_equity'] = sc1.fit_transform(df[['post_ipo_equity']])
df['post_ipo_debt'] = sc1.fit_transform(df[['post_ipo_debt']])
df['product_crowdfunding'] = sc1.fit_transform(df[['product_crowdfunding']])
df['undisclosed'] = sc1.fit_transform(df[['undisclosed']])
df['equity_crowdfunding'] = sc1.fit_transform(df[['equity_crowdfunding']])
df['seed'] = sc1.fit_transform(df[['seed']])
df['category_list'] = sc1.fit_transform(df[['category_list']])
df['founded_month'] = sc1.fit_transform(df[['founded_month']])
df['founded_quarter'] = sc1.fit_transform(df[['founded_quarter']])
df['founded_year'] = sc1.fit_transform(df[['founded_year']])
df['first_funding_at'] = sc1.fit_transform(df[['first_funding_at']])

In [316]:
df

,category_list,market,funding_total_usd,status,country_code,region,city,funding_rounds,founded_at,founded_month,...,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H
0,0.314754,0.670968,0.293233,0.0,0.976744,0.602210,0.600639,0.0,0.807692,0.842857,...,0.0,0.0,0.00,0.0,0.00000,0.0,0.0,0.0,0.0,0.0
2,0.698361,0.761290,0.636591,1.0,0.372093,0.895028,0.875399,0.0,0.836538,0.871429,...,0.0,0.0,0.00,0.0,0.00000,0.0,0.0,0.0,0.0,0.0
3,0.285246,0.322581,0.250627,1.0,0.441860,0.469613,0.488818,0.0,0.673077,0.757143,...,0.0,0.0,0.00,0.0,0.00000,0.0,0.0,0.0,0.0,0.0
8,0.836066,0.883871,0.000000,1.0,0.976744,0.850829,0.166134,0.0,0.538462,0.650000,...,0.0,0.0,0.00,0.0,0.00000,0.0,0.0,0.0,0.0,0.0
10,0.262295,0.303226,0.636591,1.0,0.186047,0.806630,0.450479,0.0,0.735577,0.807143,...,0.0,0.0,0.00,0.0,0.00000,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,0.016393,0.025806,0.002506,1.0,0.209302,0.828729,0.808307,0.2,0.317308,0.442857,...,0.0,0.0,0.05,0.0,0.00000,0.0,0.0,0.0,0.0,0.0
995,0.596721,0.664516,0.000000,1.0,0.976744,0.795580,0.153355,0.0,0.567308,0.664286,...,0.0,0.0,0.00,0.0,0.00000,0.0,0.0,0.0,0.0,0.0
997,0.308197,0.341935,0.197995,0.0,0.976744,0.480663,0.785942,0.2,0.245192,0.342857,...,0.0,0.0,0.00,0.0,0.95282,0.0,0.0,0.0,0.0,0.0
998,0.295082,0.329032,0.000000,1.0,0.744186,0.508287,0.520767,0.0,0.644231,0.735714,...,0.0,0.0,0.00,0.0,0.00000,0.0,0.0,0.0,0.0,0.0
999,0.009836,0.019355,0.834586,1.0,0.674419,0.027624,0.015974,0.0,0.735577,0.807143,...,0.0,0.0,0.00,0.0,0.00000,0.0,0.0,0.0,0.0,0.0

## Разделим выборку на обучающую и тестовую

In [317]:
goal_column='founded_at'

In [318]:
X = df.drop(goal_column, axis=1)
X

,category_list,market,funding_total_usd,status,country_code,region,city,funding_rounds,founded_month,founded_quarter,...,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H
0,0.314754,0.670968,0.293233,0.0,0.976744,0.602210,0.600639,0.0,0.842857,0.886076,...,0.0,0.0,0.00,0.0,0.00000,0.0,0.0,0.0,0.0,0.0
2,0.698361,0.761290,0.636591,1.0,0.372093,0.895028,0.875399,0.0,0.871429,0.911392,...,0.0,0.0,0.00,0.0,0.00000,0.0,0.0,0.0,0.0,0.0
3,0.285246,0.322581,0.250627,1.0,0.441860,0.469613,0.488818,0.0,0.757143,0.835443,...,0.0,0.0,0.00,0.0,0.00000,0.0,0.0,0.0,0.0,0.0
8,0.836066,0.883871,0.000000,1.0,0.976744,0.850829,0.166134,0.0,0.650000,0.772152,...,0.0,0.0,0.00,0.0,0.00000,0.0,0.0,0.0,0.0,0.0
10,0.262295,0.303226,0.636591,1.0,0.186047,0.806630,0.450479,0.0,0.807143,0.873418,...,0.0,0.0,0.00,0.0,0.00000,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,0.016393,0.025806,0.002506,1.0,0.209302,0.828729,0.808307,0.2,0.442857,0.620253,...,0.0,0.0,0.05,0.0,0.00000,0.0,0.0,0.0,0.0,0.0
995,0.596721,0.664516,0.000000,1.0,0.976744,0.795580,0.153355,0.0,0.664286,0.772152,...,0.0,0.0,0.00,0.0,0.00000,0.0,0.0,0.0,0.0,0.0
997,0.308197,0.341935,0.197995,0.0,0.976744,0.480663,0.785942,0.2,0.342857,0.518987,...,0.0,0.0,0.00,0.0,0.95282,0.0,0.0,0.0,0.0,0.0
998,0.295082,0.329032,0.000000,1.0,0.744186,0.508287,0.520767,0.0,0.735714,0.822785,...,0.0,0.0,0.00,0.0,0.00000,0.0,0.0,0.0,0.0,0.0
999,0.009836,0.019355,0.834586,1.0,0.674419,0.027624,0.015974,0.0,0.807143,0.873418,...,0.0,0.0,0.00,0.0,0.00000,0.0,0.0,0.0,0.0,0.0

In [319]:
Y = df[[goal_column]]
Y

     founded_at
0      0.807692
2      0.836538
3      0.673077
8      0.538462
10     0.735577
..          ...
994    0.317308
995    0.567308
997    0.245192
998    0.644231
999    0.735577

[629 rows x 1 columns]

In [320]:
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV

С использованием метода train_test_split разделим выборку на обучающую и тестовую

In [321]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=1)

In [322]:
print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("Y_train:", Y_train.shape)
print("Y_test:", Y_test.shape)

X_train: (503, 34)
X_test: (126, 34)
Y_train: (503, 1)
Y_test: (126, 1)

## Дерево решений

In [323]:
from sklearn.tree import DecisionTreeRegressor

In [324]:
def stat_tree(estimator):
    n_nodes = estimator.tree_.node_count
    children_left = estimator.tree_.children_left
    children_right = estimator.tree_.children_right

    node_depth = np.zeros(shape=n_nodes, dtype=np.int64)
    is_leaves = np.zeros(shape=n_nodes, dtype=bool)
    stack = [(0, -1)]  # seed is the root node id and its parent depth
    while len(stack) > 0:
        node_id, parent_depth = stack.pop()
        node_depth[node_id] = parent_depth + 1

        # If we have a test node
        if (children_left[node_id] != children_right[node_id]):
            stack.append((children_left[node_id], parent_depth + 1))
            stack.append((children_right[node_id], parent_depth + 1))
        else:
            is_leaves[node_id] = True

    print("Всего узлов:", n_nodes)
    print("Листовых узлов:", sum(is_leaves))
    print("Глубина дерева:", max(node_depth))
    print("Минимальная глубина листьев дерева:", min(node_depth[is_leaves]))
    print("Средняя глубина листьев дерева:", node_depth[is_leaves].mean())

Построим модель дерева с глубиной = 3:

In [325]:
regr5 = DecisionTreeRegressor(max_depth=3)
model5 = regr5.fit(X_train, Y_train)

Выведем основную статистику для дерева:

In [326]:
stat_tree(model5)

Всего узлов: 15
Листовых узлов: 8
Глубина дерева: 3
Минимальная глубина листьев дерева: 3
Средняя глубина листьев дерева: 3.0

И с глубиной = 5

In [342]:
regr6 = DecisionTreeRegressor(max_depth=5)
model6 = regr6.fit(X_train, Y_train)

In [343]:
stat_tree(model6)

Всего узлов: 63
Листовых узлов: 32
Глубина дерева: 5
Минимальная глубина листьев дерева: 5
Средняя глубина листьев дерева: 5.0

# Градиентный бустинг

In [345]:
regr7 = GradientBoostingRegressor(random_state=0)
model7 = regr7.fit(X_train, Y_train.values.ravel())

## Оценка качества моделей

Оценивать качество регрессии будем при помощи двух метрик - средней абсолютной ошибки (Mean Absolute Error) и медианной абсолютной ошибки (Median Absolute Error):

Средняя абсолютная ошибка (англ. Mean Absolute Error) – это степень несоответствия между фактическими и прогнозируемыми значениями. Используется с большим присутствием выбросов.

In [334]:
from sklearn.metrics import mean_absolute_error, median_absolute_error

In [335]:
err1 = []
err2 = []

In [336]:
def rate_model(model):
    print("Средняя абсолютная ошибка:",
          mean_absolute_error(Y_test, model.predict(X_test)))
    err1.append(mean_absolute_error(Y_test, model.predict(X_test)))

In [337]:
rate_model(model5)

Средняя абсолютная ошибка: 0.029933692799275942

In [346]:
rate_model(model7)

Средняя абсолютная ошибка: 0.0016676062712073444

## Вывод

Градиентный бустинг показал более точный результат по сравнению с деревом.